# Generated by Django 5.2.8 on 2025-11-29 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('separator', models.BooleanField(default=False, help_text='Show a separator line before this group.')),
                ('collapsible', models.BooleanField(default=True, help_text='Allow this group to be collapsed in the sidebar.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Drag & drop order in the sidebar.')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon', models.CharField(help_text="Material Icon name, e.g. 'dashboard', 'people', 'settings'.", max_length=50)),
                ('url_name', models.CharField(help_text="Django URL name, e.g. 'admin:auth_user_changelist' or 'myapp:myview'.", max_length=200)),
                ('url_kwargs', models.JSONField(blank=True, default=dict, help_text='Optional dict for reverse() kwargs, e.g. {"pk": 1}.')),
                ('permission_codename', models.CharField(blank=True, help_text="Optional permission codename, e.g. 'auth.view_user'. If set, user must have it.", max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Drag & drop order inside this group.')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.menugroup')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
