# Generated by Django 5.2.8 on 2025-11-29 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='permission_codename',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='url_kwargs',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='url_name',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='link',
            field=models.CharField(default=1, help_text="Final URL (e.g. '/en/admin/' or '/en/admin/auth/user/').", max_length=255),
            preserve_default=False,
        ),
    ]
