# Generated by Django 5.2.8 on 2025-11-29 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_remove_menuitem_permission_codename_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menugroup',
            options={'ordering': ['order'], 'verbose_name': 'Menu group', 'verbose_name_plural': 'Manage menu'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['order'], 'verbose_name': 'Menu item', 'verbose_name_plural': 'Menu items'},
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='icon',
            field=models.CharField(help_text="Material Icon name (e.g. 'dashboard', 'people', 'settings').", max_length=50),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='link',
            field=models.CharField(help_text='Chosen admin URL (automatically filled from a dropdown).', max_length=255),
        ),
    ]
