# Generated by Django 5.2.8 on 2025-11-29 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_menugroup_options_alter_menuitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menugroup',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Drag & drop order of the group in sidebar.'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='link',
            field=models.CharField(help_text="Admin URL (e.g. '/en/admin/auth/user/').", max_length=255),
        ),
    ]
