# Generated by Django 5.2.8 on 2025-11-29 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_menugroup_order_alter_menuitem_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='menugroup',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order of the group in sidebar.'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='link',
            field=models.CharField(help_text="Final URL, e.g. '/en/admin/auth/user/'.", max_length=255),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order inside this group.'),
        ),
    ]
