# Generated by Django 5.2.8 on 2025-11-29 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_menuitem_options_alter_menugroup_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menugroup',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order of the group in sidebar (auto-assigned).'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='icon',
            field=models.CharField(help_text="Material icon name (e.g. 'dashboard', 'people').", max_length=50),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='link',
            field=models.CharField(help_text="Final URL, e.g. '/admin/auth/user/'.", max_length=255),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order inside this group (auto-assigned).'),
        ),
    ]
