# Generated by Django 5.2.8 on 2025-11-30 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_menugroup_order_alter_menuitem_icon_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menugroup',
            options={'ordering': ['order'], 'verbose_name': 'Menu group', 'verbose_name_plural': 'Menu groups'},
        ),
    ]
