# Generated by Django 5.2.8 on 2025-11-30 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_menugroup_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menugroup',
            options={'ordering': ['order'], 'verbose_name': 'Menu group', 'verbose_name_plural': 'Manage menu'},
        ),
        migrations.AlterField(
            model_name='menugroup',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Sorting order in sidebar (auto-assigned).', verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Order inside this group (auto-assigned).', verbose_name='order'),
        ),
    ]
